steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 
          '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', 
          '--file=docker/catalogue/Dockerfile',
          '.' ]
images:
- 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest'